#### Create list

In [1]:
import numpy as np

In [2]:
v1 = np.array([0., 1., 2., 3., 4.])
print(v1)

[0. 1. 2. 3. 4.]


In [3]:
# arange(start inclusive, stop exclusive, step size)
v2 = np.arange(0, 5, dtype=float)
print(v2)

[0. 1. 2. 3. 4.]


In [4]:
# linspace( start inclusive, stop inclusive, number of elements ) 
v3 = np.linspace(0, 4, 5)
print(v3)

[0. 1. 2. 3. 4.]


In [5]:
# zeros( n ) returns a vector filled with n zeros 
v4 = np.zeros(5)
for i in range(5):
    v4[i] = i
print(v4)

[0. 1. 2. 3. 4.]


In [6]:
# read from a text file, one number per row 
# v5 = np.loadtxt("data")

#### Shape & View

In [7]:
# Generate two vectors with 12 elements each
d1 = np.linspace(0, 11, 12)
d2 = np.linspace(0, 11, 12)

In [8]:
# Reshape the first vector to a 3x4 (row x col) matrix
d1.shape = (3, 4)
print(d1)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [9]:
# Generate a matrix VIEW to the second vector
view = d2.reshape((3,4))
print(view)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [10]:
print(d2)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]


In [11]:
# Now: possible to combine the matrix and the view
d1 + view

array([[ 0.,  2.,  4.,  6.],
       [ 8., 10., 12., 14.],
       [16., 18., 20., 22.]])

In [12]:
# Element access: [row,col] for matrix
print(d1[0,1])
print(view[0,1])
print(d2[1])

1.0
1.0
1.0


In [13]:
print(d1.shape)
print(view.shape)
print(d2.shape)

(3, 4)
(3, 4)
(12,)


In [14]:
print(d1.ndim)
print(np.rank(d1))

2
2


/Users/shawlu/anaconda3/lib/python3.5/site-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  


#### Indexing (return views)

In [15]:
# Create a 12-element vector and reshape into 3x4 matrix
d = np.linspace(0, 11, 12)
d.shape = (3, 4)
print(d)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [16]:
# first row
print(d[0,:])

# Second col
print(d[:,1])

# Individual element: scalar
print(d[0,1])

# Subvector of shape 1
print(d[0:1,1])

# Subarray of shape 1x1
print(d[0:1,1:2])

[0. 1. 2. 3.]
[1. 5. 9.]
1.0
[1.]
[[1.]]


In [17]:
# return views, not copies
view = d[:,1]
view[2] = 999
print(d)

[[  0.   1.   2.   3.]
 [  4.   5.   6.   7.]
 [  8. 999.  10.  11.]]


#### Slicing (return copies)

In [18]:
# Integer indexing: third and first column
print(d[:, [2,0]])

# Boolean indexing: second and third rows
k = np.array([False, True, True])
print(d[k, :])

[[ 2.  0.]
 [ 6.  4.]
 [10.  8.]]
[[  4.   5.   6.   7.]
 [  8. 999.  10.  11.]]


In [19]:
copy = d[:, [2,0]]
copy[0, 1] = 888

print(copy)
print(d)

[[  2. 888.]
 [  6.   4.]
 [ 10.   8.]]
[[  0.   1.   2.   3.]
 [  4.   5.   6.   7.]
 [  8. 999.  10.  11.]]


In [3]:
A = np.random.randn(4,3)

# collapse second dimension
print(np.sum(A, axis = 1, keepdims = True).shape)

# collapse first dimension
print(np.sum(A, axis = 0, keepdims = True).shape)

(4, 1)
(1, 3)
